-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           8.0.30 - MySQL Community Server - GPL
-- OS do Servidor:               Win64
-- HeidiSQL Versão:              12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Copiando estrutura do banco de dados para petcom59_petcomp_db
CREATE DATABASE IF NOT EXISTS `petcom59_petcomp_db` /*!40100 DEFAULT CHARACTER SET utf8mb3 */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `petcom59_petcomp_db`;

-- Copiando estrutura para tabela petcom59_petcomp_db.noticias
CREATE TABLE IF NOT EXISTS `noticias` (
  `id` int NOT NULL AUTO_INCREMENT,
  `titulo` varchar(500) NOT NULL,
  `texto` text NOT NULL,
  `data` date NOT NULL,
  `foto` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8mb3;

-- Copiando dados para a tabela petcom59_petcomp_db.noticias: ~26 rows (aproximadamente)
REPLACE INTO `noticias` (`id`, `titulo`, `texto`, `data`, `foto`) VALUES
	(1, 'Nova Publicação: Quando os Discentes se Expressam: Um Relato de Experiência da Criação de um Podcast para Aumentar o Engajamento e Troca de Conhecimento em Tempos de Pandemia', 'Melhorar o engajamento de discentes e facilitar o acesso à informação têm se tornado mais relevantes no contexto educacional. Em virtude do isolamento social gerado pela pandemia da COVID-19, recursos didáticos como podcasts e vídeos podem ser explorados para alcançar este objetivo. Com o intuito manter os discentes atualizados e engajados durante o ensino remoto, o grupo PETComp da Universidade Federal do Maranhão montou uma equipe para desenvolver um podcast sobre conteúdos relacionados à Tecnologia da Informação. Este artigo apresenta o processo de produção dos episódios do podcast. Após a preparação do material e lançamento do podcast em plataformas digitais, foi coletada a opinião dos discentes sobre o mesmo através de um questionário. Os resultados indicam que o podcast contribuiu para disponibilizar conteúdos construídos pelos discentes de forma descontraída, permitindo a atualização em temas relevantes e o engajamento dos ouvintes.', '2021-07-20', ''),
	(2, 'Nova Publicação: O Impacto das Atividades do Grupo PET no Aprimoramento de Soft Skills Requeridos pelo Mercado de Computação do Maranhão: Uma Análise da Visão dos Discentes', 'O profissional de computação precisa adquirir as mais variadas habilidades para se manter competitivo no mercado de trabalho. Entre essas habilidades, as denominadas soft skills (ou habilidades não técnicas) são atributos pessoais que permitem ao indivíduo desempenhar uma boa interação com o mundo ao seu redor. Nesse contexto, o Programa de Educação Tutorial (PET) surge como uma alternativa para desenvolver tais habilidades durante o ensino superior. No entanto, existem poucas análises sobre como um discente pode desenvolver soft skills durante a realização de atividades no âmbito do PET. Neste artigo, através de um formulário, foi obtida a percepção dos discentes sobre o impacto das atividades realizadas no PET para o desenvolvimento de soft skills, considerando o contexto do estado do Maranhão. Os resultados apontam para o impacto positivo das atividades do programa para este fim, além de identificar oportunidades de melhoria.', '2021-07-20', ''),
	(3, 'Nova Publicação: Quando a Aluna se Torna a Mestre: Um Relato da Experiência de Alunas de Graduação Aplicando Dinâmicas de Ensino de Computação para Alunas de Ensino Médio', 'O quantitativo de mulheres nas carreiras e cursos das áreas de Computação e Tecnologias é baixo se comparado ao quantitativo de homens. Para incentivá-las a entrar em cursos de exatas, vários projetos de extensão têm sido executados. Nesse contexto, o presente artigo relata os resultados da aplicação de uma gincana em que foram realizadas atividades de ensino envolvendo computação plugada e desplugada. As atividades e o material preparado foram escolhidos e adaptados por alunas do curso de ciência da computação da Universidade Federal do Maranhão com o intuito de encorajar alunas de ensino médio. Como resultado desta experiência, foi possível coletar opiniões sobre o processo de criação da gincana por parte das graduandas e a avaliação da mesma por parte de alunas de ensino médio.', '2020-06-30', ''),
	(4, 'Alunos ingressantes em cursos de ensino superior sentem dificuldade em se adaptar à nova modalidade de ensino. Nesse contexto, o evento da Semana do Calouro é realizado pelos discentes do grupo PET de Ciência da Computação da Universidade Federal do Maranhão acompanhados por professores como uma atividade de integração aos novos discentes do curso de Ciência da Computação. Este artigo relata a experiência de aplicar diversas atividades com o intuito de esclarecer as dúvidas geradas pelo ingresso', 'Alunos ingressantes em cursos de ensino superior sentem dificuldade em se adaptar à nova modalidade de ensino. Nesse contexto, o evento da Semana do Calouro é realizado pelos discentes do grupo PET de Ciência da Computação da Universidade Federal do Maranhão acompanhados por professores como uma atividade de integração aos novos discentes do curso de Ciência da Computação. Este artigo relata a experiência de aplicar diversas atividades com o intuito de esclarecer as dúvidas geradas pelo ingresso no novo ambiente, bem como aumentara visibilidade dos contextos do curso. Ao término das atividades, o feedback dos discentes apontou para a utilidade das mesmas para conhecer as oportunidades dentro da universidade em termos de projetos, pesquisas e áreas de atuação, assim como soluções para problemas que surgiram durante sua execução.', '2020-06-30', ''),
	(5, 'Nova Publicação: Identificação das Expectativas e Dificuldades de Alunos de Graduação no Ensino de Engenharia de Software', 'A Engenharia de Software visa apoiar o desenvolvimento de sistemas computacionais de qualidade, reduzindo os custos de produção e aumentando a produtividade dos profissionais. Buscar entender as necessidades dos alunos iniciantes nessa área da computação é vital para propor metodologias adequadas de ensino. Este artigo apresenta o resultado da aplicação de um questionário quanto à experiência dos alunos de uma disciplina introdutória de Engenharia de Software. Foi capturada a expectativa de alunos que ainda não cursaram a disciplina, assim como a visão de alunos que já a cursaram, reprovando ou não. Os resultados desta pesquisa permitiram identificar eventuais aspectos que possam ter influência positiva ou negativa no processo de aprendizado.', '2019-07-12', ''),
	(6, 'Nova Publicação: Educação Tutorial em Computação: Uma Análise Retrospectiva das Atividades Realizadas para a Formação Pessoal e Profissional de Cientistas da Computação', 'O Programa de Educação Tutorial (PET) atua como uma iniciativa de promover a formação integrada de todos os atores envolvidos combatendo a evasão, estimulando o desenvolvimento criativo e empreendedor, assim como a continuação para níveis superiores de formação acadêmica. Apesar da existência de 37 grupos PET na área de computação segundo a Sociedade Brasileira de Computação (SBC), poucos grupos divulgam os resultados das ações realizadas em eventos científicos da computação para discutir suas implicações. Nesse contexto, este trabalho apresenta uma análise das atividades desenvolvidas em um grupo PET de Ciência da Computação do ponto de vista dos discentes. Os resultados apontam o impacto das atividades na formação dos alunos, lições aprendidas e oportunidades de melhoria para o sucesso das atividades.', '2019-07-12', ''),
	(7, 'Nova Publicação: Educação Tutorial em Ciência da Computação: uma proposta de sistematização', 'No intuito de proporcionar a formação acadêmica ampla e de qualidade, o Programa de Educação Tutorial (PET) é um modelo indissociável de ensino, pesquisa e extensão, que preza também por valores de cidadania e consciência social. Apesar de existir desde a década de 90, com o nome de Programa Especial de Treinamento, e ter se expandido para mais de 37 grupos na área de Computação, pouca ou nenhuma literatura tem sido produzida com intuito de prover uma base metodológica de atuação desses grupos. Este artigo descreve métodos e práticas que têm sido utilizados com êxito pelo PET de Ciência da Computação da Universidade Federal do Maranhão (PETComp/ UFMA) no desenvolvimento de suas atividades, aprimorados ao longo de seus oito anos de existência.', '2015-07-20', ''),
	(8, 'Atenção Petianos! Está Aberto as Inscrições e Submissões do XXII ENEPET', 'O XXII Encontro Nordestino dos Grupos do Programa de Educação Tutorial (ENEPET) promoverá a troca de experiências entre discentes e tutores nordestinos por meio de assembleias, grupos de discussão e apresentação de trabalhos acadêmicos. O evento, sediado pela Universidade Federal da Paraíba (UFPB), ocorrerá de forma on-line nos dias 30/08 a 01/09. A edição atual, com o tema "Inteligência Artificial, desinformação e ética científica: um debate necessário", busca fomentar discussões sobre a desinformação no contexto das universidades públicas brasileiras.\r\n\r\nHospedado virtualmente pelas plataformas YouTube e GoogleMeet. O evento abordará diversas temáticas, incluindo a responsabilidade social do Programa de Educação Tutorial, a regulamentação do uso da Inteligência Artificial, além do desenvolvimento de ações afirmativas e a atuação do PET no ambiente escolar. Também é posta em discussão os direitos digitais e a autenticidade nos trabalhos acadêmicos.\r\n\r\nDevido à sua abordagem multidisciplinar, o evento contemplará diversas esferas do conhecimento, proporcionando a oportunidade para que todos encontrem seus temas de interesse. Essa abertura possibilitará a troca de conhecimentos entre diferentes áreas, permitindo diálogos que vão além dos limites da esfera acadêmica.\r\n\r\nPara aqueles que desejam apresentar seus projetos de pesquisa, a submissão de trabalhos científicos foi prorrogada até o dia 4 de julho. Consulte o edital para obter mais informações sobre as diretrizes de envio.\r\n\r\nPara mais informações sobre o evento, não deixem de conferir a programação completa e de se inscreverem no site do evento. Segue também a rede social em que será publicada qualquer atualização sobre ENEPET nessa edição de 2023.', '2023-07-01', './assets/images/noticias/enepet.png'),
	(9, 'Atenção Petianos! Está Aberto as Inscrições e Submissões para o ENAPET 2023\r\n', 'A 28ª edição do Encontro Nacional do Programa de Educação Tutorial (ENAPET) está marcada para acontecer nos dias 27 e 28 de outubro e 2, 3 e 4 de novembro de 2023, promovido pela Universidade Federal do Triângulo Mineiro (UFTM). Este ano, o evento será realizado de forma remota, proporcionando a participação de discentes, docentes e interlocutores vinculados ao programa de qualquer parte do país.\r\n\r\nO principal objetivo do ENAPET é promover a discussão coletiva de temas e questões relevantes para a manutenção e o desenvolvimento do Programa de Educação Tutorial (PET) em âmbito nacional. Como parte do planejamento do PET, o evento visa estimular e aprimorar os cursos de graduação oferecidos pelas universidades públicas, assim como fortalecer as ações voltadas à comunidade.\r\n\r\nNesta edição, o ENAPET focará nos desafios enfrentados pela permanência estudantil. Sob o tema "Programa de Educação Tutorial: Os desafios da permanência estudantil", o evento busca explorar e discutir a relevância do PET para a educação brasileira e sua importância em outros âmbitos da sociedade.\r\n\r\nAlém disso, o evento contará com uma variedade de atividades, incluindo grupos de discussão, apresentações de trabalhos, oficinas e minicursos. Essas atividades proporcionarão um espaço propício para que os participantes compartilhem experiências, troquem conhecimentos e contribuam para o fortalecimento do PET.\r\n\r\nOs interessados em participar do ENAPET 2023 podem acessar informações detalhadas sobre o cronograma, programação, inscrições e submissões de trabalhos através do site oficial do evento. \r\n\r\nEsperamos a participação de todos os envolvidos com o Programa de Educação Tutorial, contribuindo para o enriquecimento das discussões e fortalecimento desse importante programa para a educação brasileira. Junte-se a nós nesse evento que visa não apenas discutir desafios, mas também buscar soluções e promover o crescimento conjunto.', '2023-07-01', './assets/images/noticias/enapet.png'),
	(10, 'Novo Episódio do PodComp está no Ar: Cibersegurança #12\r\n\r\n', 'O PodComp vem sendo realizado como forma de divulgar notícias do mundo da tecnologia assim como debater questões atuais que permeiam a área de uma forma bem descontraída e interativa com os ouvintes.\r\n\r\nNesse contexto, a cibersegurança é um tema cada vez mais relevante na atualidade, onde dados são predominantemente digitais. Basicamente, esse tema versa sobre proteger as suas informações na internet e garantir que nenhum dado caia nas mãos erradas. O corrompimento de informações na rede gera bilhões de dólares de prejuízo todos os anos, e  a segurança sobre esses dados têm recebido mais atenção de organizações e governos a cada ano.\r\n\r\nNesse novo episódio, os petianos André Luíz, Mikael e Thiago exploram o conceito de cibersegurança e discutem a relevância disso na atualidade, as principais subdivisões do tema e como isso afeta o dia a dia de quem vive na internet. Entre os pontos discutidos estão dicas práticas de como se proteger enquanto navegando na internet, assim como as experiências pessoais dos locutores no que diz respeito à segurança virtual.\r\n\r\nAcesse a esse podcast e muitos outros no perfil oficial do PodComp', '2023-08-07', './assets/images/noticias/pod-ciberseguranca.png'),
	(11, 'Evento Petcomp: Acalourada 2023.2 Realizada para Recepcionar e Auxiliar os Calouros', 'O semestre de 2023.2 chegou e o PETComp já realizou sua tradicional recepção de calouros, chamada de Acalourada. Durante os dias 23, 24 e 25 de agosto, os petianos organizaram o evento que contou com a presença de professores do curso de Ciência da Computação, palestras, tour em laboratórios e dinâmicas em grupo.\r\n\r\nA Acalourada tem como principal objetivo garantir a integração dos novos discentes ao curso e ao ambiente universitário, visto que muitos deles acabaram de sair do ensino médio. Portanto, nada melhor do que oferecer-lhes, em sua primeira semana universitária, um local onde possam tirar dúvidas e esclarecer pensamentos junto aos seus veteranos e professores.\r\n\r\nApós a realização da Acalourada, o PETComp sempre busca avaliar o que os calouros acharam e o que tiraram de proveito do evento. Alguns dos pontos que eles mais ressaltaram durante nossa pesquisa de satisfação foram o conhecimento adquirido sobre o curso e suas diversas oportunidades, além de afirmarem que a Acalourada é um meio que impactará positivamente em sua permanência no curso de Ciência da Computação.\r\n', '2023-08-23', './assets/images/noticias/acalourada1.jpeg|./assets/images/noticias/acalourada2.jpeg'),
	(12, 'PETComp Oferece Oficina de Jogos Digitais com Scratch na Acalourada 2023.2\r\n', 'Pensando a princípio no desenvolvimento dos conceitos iniciais da programação, o Scratch é uma plataforma que se concentra em um estilo de programação em blocos, que nada mais é do que uma metodologia visualmente mais agradável, no qual as ferramentas para o desenvolvimento são blocos coloridos que substitui as usuais linguagens de programação. Criado como um projeto do Grupo Lifelong Kindergarten no MIT Media Lab, desenvolvido pela Scratch Foundation, seus objetivos vão além da programação, sendo amplamente utilizado para produção de jogos, animações e histórias interativas.\r\n\r\nCom todos esses aspectos, o PETComp elaborou uma oficina de jogos digitais efetuada no último evento organizado pelo petianos, a acalourada 2023.2, que reuniu os mais novos ingressantes do curso de Ciência da Computação da UFMA. Realizada nos dias 23, 24 e 25 de agosto, dispôs de diversas atividades, incluindo a execução da oficina, na qual foi ministrada por um dos petianos, dando em seguida oportunidade para os jovens universitários produzirem seus próprios jogos e animações mediante uma competição amigável entre os calouros, de forma que mesmo aqueles que nunca tiveram nenhum contato com a programação pudessem participar e de fato programar.    \r\n\r\nSabemos que para muitos jovens a universidade é um lugar novo e desconhecido, o qual pode se tornar um grande desafio quando embarcados sem nenhum conhecimento prévio da graduação escolhida. Casos assim, na maioria das vezes aumenta o percentual de evasão no curso, que de maneira triste já é bem alta. Oficinas como a desenvolvida visam minimizar essa taxa e gerar uma mudança de cenário no que se refere aos graduandos, mostrar que a programação abre as portas para todas as pessoas dispostas a aprender.\r\n\r\nComo resultado dessa parceria e trabalho, os participantes apresentaram opiniões positivas em relação à oficina ofertada, por exemplo, argumentando como a princípio alguns possuíram dificuldades no uso da plataforma, sendo seu primeiro contato com a programação em bloco, todavia essa dificuldade foi ultrapassada e os estudantes conseguiram mostrar seus trabalhos gerando um ambiente de aprendizado descontraído e enriquecedor.\r\n\r\nMais informações sobre minicursos e oficinas acesse o site do PETComp: ', '2023-08-23', './assets/images/noticias/oficina-jogos.jpg|./assets/images/noticias/oficina-jogos2.jpeg'),
	(13, 'PETComp Anuncia a Continuidade das Monitorias de Cálculo I, Algoritmos I e Linguagem de Programação I para Aprimorar o Aprendizado dos Discentes.', 'Nesse novo semestre de 2023.2, o PETComp anuncia que dará continuidade às monitorias de Cálculo I, Algoritmos I e Linguagem de Programação I. \r\n\r\nA iniciativa teve início devido ao problema da evasão dos discentes dos cursos de Tecnologia, que acontece a nível nacional. Com a realização das monitorias dessas disciplinas, se percebeu um aumento do interesse pelas mesmas assim como melhores resultados nas avaliações. O feedback dos participantes da monitoria é muito importante, sendo obtido através de formulários, preenchidos pelos discentes ao final do semestre, que irão relatar suas experiências com a monitoria, pontos a serem melhorados e o quanto essa participação foi proveitosa.\r\n\r\nCada monitoria possui um formato de aulas híbridas com enfoque em resolução de exercícios práticos e análise de provas antigas. Nesse ambiente de monitoria, os discentes são estimulados a colaborarem ativamente com o monitor, resolvendo os exemplos propostos por ele enquanto também tiram suas dúvidas.\r\n\r\nO principal objetivo almejado pela realização das monitorias é despertar o interesse dos discentes pelas disciplinas que servirão como base pro restante do curso. Pensando nisso, os monitores são preparados para manterem um contato mais próximo com os participantes e fora do horário das aulas continuam disponíveis para tirarem qualquer dúvida referente à disciplina. O PETComp acredita que essa iniciativa é essencial para que os estudantes se sintam motivados com o curso.', '2023-08-28', './assets/images/noticias/monitoria-cont.png|./assets/images/noticias/monitoria-cont2.png'),
	(14, 'PETComp Anuncia Novas Monitorias de Estrutura de Dados I e Matemática Discreta e Lógica', 'Com a chegada do novo semestre de 2023.2, o PETComp também anuncia a criação de duas novas monitorias: Estrutura de Dados I e Matemática Discreta e Lógica.\r\n\r\nLevando em consideração a opinião dos discentes do curso e após uma análise buscando ponderar as principais dificuldades enfrentadas com relação às disciplinas da grade curricular, as matérias escolhidas para as novas monitorias foram a de Estrutura de Dados I e a de Matemática Discreta e Lógica. Após essas novas adições, o PETComp passa a oferecer as monitorias de: Cálculo I, Algoritmos I, Linguagem de Programação I, Estrutura de Dados I e Matemática Discreta e Lógica.\r\n\r\nAs novas monitorias funcionarão assim como as que já existiam, no formato híbrido, sendo ministradas presencialmente e com transmissão via Google Meet. As aulas serão gravadas e disponibilizadas aos alunos que não puderam participar ou que desejam rever a aula do dia. As aulas terão um momento expositivo, o qual o conteúdo será ministrado, e outro momento (este com mais enfoque) de resolução de exercícios, revisão de avaliações passadas e um tira-dúvidas com os discentes.\r\n\r\nO objetivo das monitorias é elevar a qualidade do desenvolvimento acadêmico dos discentes e auxiliar na formação dos mesmos, tentando aumentar o interesse, o engajamento e a compreensão acerca dos conteúdos abordados durante o curso, utilizando para isso uma abordagem simplificada de aluno para aluno, com trocas de experiências e conhecimentos. Essa abordagem vem mostrando-se ser bem eficaz, levando em conta o feedback dos discentes que são colhidos a cada final de semestre.\r\n\r\nPara saber mais sobre as nossas monitorias, acesse a página das monitorias:', '2023-08-28', './assets/images/noticias/ed1.png|./assets/images/noticias/Mdl.png'),
	(15, 'Evento PetComp: Feira das Profissões 2023 Terá Abertura Nesta Terça-Feira\r\n', 'Já é tradição da Universidade Federal do Maranhão (UFMA) realizar, anualmente, a feira das profissões que tem por objetivo orientar estudantes do Ensino Médio e demais interessados que realizarão o Exame Nacional do Ensino Médio (ENEM), condição para o acesso às vagas do Sistema de Seleção Unificada (SiSU), a decidir qual curso seguir e que profissional intencionam ser.\r\n\r\nE nesta terça-feira, 19, será realizada, a partir das 14h, a abertura da Feira das Profissões 2023 da Universidade Federal do Maranhão (UFMA), que ocorrerá até o dia 21 de setembro, no Centro de Convenções da UFMA, Campus São Luís.\r\n\r\nA feira contará com apresentação dos cursos de graduação da UFMA, suas produções e inserção profissional no mundo do trabalho; atividades culturais; atração dos cursos de graduação e tour com visita in loco pelo campus universitário.\r\n\r\nConfira a programação completa abaixo, para mais informações sobre o evento acesse o site da feira das profissões.', '2023-09-18', './assets/images/noticias/feira-profissoes.jpg'),
	(16, 'PETComp Promoverá Palestra Sobre Lógica de Programação para o LABI (Liga Acadêmica de Bioinformática)', 'No dia 27 de outubro, o PETComp realizará uma palestra para a Liga Acadêmica de Bioinformática com o intuito de oferecer conhecimentos básicos de lógica de programação, o funcionamento de algoritmos e apresentar algumas linguagens de programação que podem ser usadas no dia a dia de um programador, além de introduzir ferramentas de estudo/ensino de programação geralmente utilizadas no início do aprendizado.\r\n\r\nO PETComp busca, por meio de experiências como essa, quebrar uma barreira existente em relação à tecnologia para aqueles que não estão necessariamente envolvidos na bolha da tecnologia, apresentando-a como algo acessível e compreensível, tentando mostrar como a lógica por trás de computadores e aplicativos que utilizamos diariamente pode ser muito simples.', '2023-10-28', './assets/images/noticias/palestra-bio.jpg|./assets/images/noticias/palestra-bio2.jpeg'),
	(17, 'PETComp Inicia Novo Projeto, Confecção de Esculturas Paper Craft', 'O papercraft é um método de construção de objetos tridimensionais a partir de papel, assemelhando-se ao origami. No entanto, ele se diferencia ao utilizar diversos pedaços de papel, os quais são cortados com tesoura e unidos por meio de cola, em vez de se sustentarem de forma individual proveniente geralmente de um único pedaço de papel. \r\n\r\nO PET Computação explorou essa técnica para criar uma exposição visual cativante e educativa: uma linha do tempo de computadores. O objetivo principal dessa iniciativa foi mostrar a evolução histórica dos hardwares que transformaram a interação das pessoas com os PCs ao longo do tempo.\r\n\r\nA exposição abrange um período significativo, começando nos anos 1970 com o icônico Commodore PET e estendendo-se até o início dos anos 2000 com o renomado Nintendo GameCube. Entre essa linha do tempo, uma variedade de dispositivos representa momentos-chave que contribuíram para a formação dos desktops modernos, moldando a maneira como os computadores são compreendidos e utilizados nos dias de hoje.\r\n\r\nEmbora o local específico para a exposição ainda não tenha sido definido, em breve, essas obras de papercraft estarão disponíveis para apresentação em breve. Acompanhe as atualizações sobre os detalhes e datas de exibição consultando as atualizações no site oficial do PETComp.', '2023-12-01', './assets/images/noticias/papercraft.jpg|./assets/images/noticias/papercraft2.jpeg'),
	(18, 'Novo Seletivo PETComp Será Aberto para 2023.2', 'O processo seletivo do Programa de Educação Tutorial de Ciência da Computação da Universidade Federal do Maranhão para o próximo semestre letivo está prestes a começar, um programa que se iniciou em 1 de setembro de 2007 e já beneficiou cerca de 246 discentes, tendo atualmente como tutor o professor Luis Rivero. O projeto tem como base fundamental a orientação dos estudantes do curso, possibilitando uma ampla formação acadêmica, incluindo pesquisa, ensino e extensão. Além disso, a organização dos alunos em grupo proporciona uma experiência única na passagem pela universidade, acarretando inúmeras oportunidades profissionais.\r\n\r\nA proposta do projeto é elevar a formação acadêmica dos estudantes da graduação, estimulando o pensamento crítico e alta qualificação técnica, científica e tecnológica. Esse esforço em conjunto com professores e alunos vêm apresentando grandes resultados em pesquisas, mas não apenas nesse âmbito, os petianos também são responsáveis pela organização e execução de acaloradas, monitorias e desenvolvimento de software.    \r\n\r\nCom todos esses benefícios o PETComp vem convidar a todos a participar da seleção para novos petianos, as inscrições ocorrerão nos dias 15 a 17 de dezembro e o seletivo acontecerá do dia 18 ao dia 20 do mesmo mês, todo processo será realizado de forma remota. O programa dispõe de 7 vagas, entre elas um bolsista, a bolsa será do primeiro lugar na classificação. É necessário ter os critérios básicos para participar do processo seletivo, o estudante precisa estar entre o 2º e 6º período, também deve possuir um coeficiente de rendimento (CR) igual ou superior a 6,0, além de ter disponibilidade 20 h semanais para realização das atividades no turno matutino. O resultado será divulgado na página oficial do PETcomp no Instagram dia 21 de dezembro.\r\n\r\nPara mais informações sobre o processo seletivo consulte o edital.\r\n\r\nSiga-nos nas redes sociais: @petcompufma', '2023-12-15', './assets/images/noticias/seletivo.png'),
	(19, 'Nova Publicação: O Impacto das Monitorias Acadêmicas Na Formação De Alunos De Ciência Da Computação: Um Relato do PETComp UFMA', 'No contexto do curso de Ciência da Computação, os novos alunos enfrentam desafios significativos ao ingressarem no ensino superior. Para apoiá-los durante essa transição crucial, as monitorias oferecidas pelo PETComp da Universidade Federal do Maranhão (UFMA) desempenham um papel central, visando proporcionar suporte personalizado e efetivo.\r\n\r\nAs monitorias têm como objetivo auxiliar os estudantes em disciplinas específicas, como Cálculo I, Algoritmos I e Linguagem de Programação I. Implementadas de forma híbrida, combinando aulas presenciais e online, com todas as sessões sendo gravadas, essas monitorias procuram superar as dificuldades iniciais e oferecer um suporte personalizado de aprendizagem.\r\n\r\nAmbos, estudantes e monitores se beneficiam com as monitorias. Aos estudantes, a participação em monitorias oferece oportunidade de aprimorar habilidades essenciais, tais como organização, autonomia e técnicas de estudo. Essas competências desempenham um papel fundamental no sucesso acadêmico e na preparação para futuras carreiras profissionais. Para os monitores, essa experiência extracurricular proporciona um ambiente propício para o desenvolvimento de competências em liderança, comunicação e ensino. Ao auxiliarem seus colegas, os monitores adquirem habilidades valiosas que beneficiam tanto sua vida acadêmica quanto suas futuras trajetórias profissionais.\r\n\r\nEste artigo relata a experiência do grupo PET de Computação da UFMA (PETComp) na realização de monitorias para os alunos do curso, com um planejamento cuidadoso, fornecendo suporte personalizado aos estudantes. Foram aplicados formulários online tanto para os monitores quanto para os novos discentes, com o intuito de obter avaliações sobre o desempenho, relato e satisfação das monitorias. Foi constatado o impacto positivo das monitorias no apoio aos alunos, auxiliando-os a superar desafios acadêmicos e fortalecendo a comunidade educacional. O artigo convida os leitores a explorar como as monitorias do PETComp têm feito a diferença na vida acadêmica dos estudantes de Ciência da Computação, transformando desafios em oportunidades e promovendo um ambiente de aprendizagem enriquecedor\r\n\r\nAutores: Melquezedeque Costa, Maxwell Pires, Rick Santos, Luis Rivero ', '2023-11-14', './assets/images/monitoria-photo-2.jpg|./assets/images/monitoria-photo-4.jpg'),
	(20, 'Nova Publicação: Explorando o Pensamento Computacional Através de Jogos Educacionais Desplugados', 'A Acalourada é uma atividade de recepção dos estudantes ingressantes no curso de Ciência da Computação de forma presencial. Essa atividade já vem sendo desenvolvida de forma presencial há mais de 6 anos em conjunto com a Coordenação de Computação, o Departamento de Informática e o PET de Computação, e procura guiar os calouros através da universidade e do curso. Em todas as edições, o PETComp procura maneiras de aprimorar o evento, tornando-o mais relevante, estimulante  e interativo, partindo dessa premissa, foram desenvolvidos os chamados Jogos Desplugados.\r\n\r\nMuitos alunos ingressam no curso de Ciência da Computação sem conhecimento prévio de computação e conceitos básicos do Pensamento Computacional, e para combater esse desafio, o PETComp aplicou pela primeira vez os jogos durante a Recepção dos Calouros 2023.1\r\n\r\nOs Jogos Desplugados, referem-se a jogos que não dependem de aparelhos eletrônicos que visa introduzir os novos alunos aos conceitos de Pensamento Computacional e desenvolver habilidades essenciais ao curso de Computação. onde Cada um aborda um conceito de computação. Dentre os jogos aplicados, destacamos três: Algoritmizando-se, Bingo Binário e Resolve pra Mim?.\r\n\r\nAo final das atividades, foi possível verificar uma maior compreensão dos conceitos por meio da abordagem prática dos jogos. Este artigo descreve o funcionamento desses três jogos e apresenta o processo de aplicação e compartilha as percepções dos discentes sobre a eficácia dos mesmos. Conclui-se que é necessário dar continuidade a essas práticas, levando em consideração as sugestões dos alunos para futuras melhorias visando facilitar a jornada acadêmica dos ingressantes.\r\n\r\nA versão completa do artigo está programada para ser publicada durante o Encontro Nacional dos Grupos PET de 2024 (ENAPET 2024).\r\n\r\nAutores: Joana Kuelvia de Araujo Silva, André Luiz Ribeiro de Araujo Lima, Sabryna Rodrigues Araujo, Adriano França Monteiro, Luis Jorge Enrique Rivero Cabrejos', '2023-11-14', './assets/images/noticias/pensComp1.jpeg|./assets/images/noticias/pensComp2.jpg'),
	(21, 'Resultado do Processo Seletivo para o PETComp: Novos Integrantes Selecionados!', 'É com grande satisfação que divulgamos o resultado do Processo Seletivo para o Programa de Educação Tutorial em Computação (PETComp) da Universidade Federal do Maranhão. Após uma cuidadosa análise das inscrições e a realização das etapas seletivas, temos o prazer de anunciar os novos integrantes que se destacaram durante o processo.\r\n\r\nParabenizamos todos os participantes pela inscrição, empenho e dedicação durante o processo seletivo, que consistiu em duas etapas, sendo elas formulário e um desafio, respectivamente. No desafio, os candidatos puderam escolher entre monitoria, desenvolvimento e podcast . Para os novos integrantes, aguardamos ansiosamente para recebê-los em nossa equipe e iniciarmos juntos uma jornada de aprendizado, pesquisa e contribuição para a comunidade acadêmica.', '2023-12-21', './assets/images/noticias/resultSel.png'),
	(22, 'Novo episódio do PodComp está no ar: "ChatGPT Vai Roubar Seu Emprego?"', 'O PodComp tem como principal objetivo oferecer aos estudantes de computação ou qualquer pessoa interessada no mundo da tecnologia a oportunidade de ficar por dentro dos tópicos que os próprios estudantes e futuros trabalhadores da área de tecnologia julgam essenciais a serem discutidos, por meio de uma ferramenta que está sempre na palma da mão.\r\n\r\nNo episódio #11 do PodComp, o tópico discutido foi o polêmico ChatGPT, a inteligência artificial que surgiu em meados de 2020 e desde então tem ocupado cada vez mais espaço dentro do ambiente acadêmico. Mas a pergunta que os petianos querem realmente responder é: O ChatGPT vai roubar nossos empregos?\r\n\r\nDurante todo o episódio, os ouvintes poderão saber como estudantes de graduação em Ciência da Computação têm usado a IA do momento para ajudá-los a estudar e resolver problemas, além de refletir sobre algumas problemáticas levantadas quanto à confiabilidade da ferramenta e, claro, responder sobre como o surgimento de inteligências artificiais cada vez mais eficientes pode implicar no dia a dia e no trabalho de um programador.\r\n\r\nConfira nosso episódio inédito no Spotify e fique por dentro do que podemos esperar dessa nova forma de resolver problemas que o ChatGPT nos oferece.\r\n\r\nAcesse a esse podcast e muitos outros no perfil oficial do PodComp.', '2023-05-22', 'assets/images/noticias/pod-gpt.png'),
	(23, 'Novo Episódio do PodComp está no Ar: Carreiras em TI #13', 'O PodComp, canal de podcast produzido pelo grupo estudantil PETComp da Universidade Federal do Maranhão (UFMA), lançou hoje um novo episódio dedicado ao tema das carreiras em Tecnologia da Informação (TI). Com o intuito de fornecer insights valiosos para estudantes e profissionais interessados em ingressar ou progredir neste campo, o episódio aborda diversos aspectos relacionados às oportunidades e desafios das carreiras em TI.\r\n\r\nO episódio, que conta com a participação dos petianos Breno Vidigal, Paloma Santos, Melquezedeque Costa e Thiago Augusto, oferece uma visão abrangente das diversas áreas de atuação dentro da TI, destacando as tendências do mercado de trabalho e as habilidades essenciais necessárias para o sucesso profissional. Além disso, são discutidas questões pertinentes, como as demandas do mercado de trabalho, as diferentes trajetórias de carreira disponíveis e as perspectivas futuras da indústria de tecnologia.\r\n\r\nO novo episódio já está disponível no Spotify! Para aqueles interessados em explorar as oportunidades e desafios das carreiras em TI, o episódio promete oferecer uma fonte valiosa de informações e reflexões para orientar suas escolhas e aspirações profissionais.', '2024-02-06', './assets/images/noticias/pod-carreiras.png'),
	(24, 'PETComp da UFMA Realiza Coleta de Alimentos e Roupas para Doação ao Rio Grande do Sul', 'O Programa de Educação Tutorial do Curso de Ciência da Computação da Universidade Federal do Maranhão (PETComp UFMA) promoveu uma campanha solidária de arrecadação de alimentos e roupas destinados às vítimas das enchentes no Rio Grande do Sul. A ação, que mobilizou estudantes, professores e a comunidade acadêmica em geral, busca amenizar os impactos da tragédia que atingiu milhares de pessoas no estado.\r\nRecentemente, o Rio Grande do Sul foi devastado por intensas chuvas, que causaram enchentes e deslizamentos de terra, resultando em perdas humanas, destruição de residências e infraestruturas. Famílias inteiras ficaram desabrigadas, necessitando urgentemente de ajuda humanitária para enfrentar a difícil situação. A tragédia gerou uma onda de solidariedade em todo o Brasil, com diversas iniciativas de apoio às vítimas.\r\n\r\nDiante desse cenário, o PETComp decidiu organizar uma campanha de arrecadação, reconhecendo a importância de contribuir para aliviar o sofrimento das pessoas afetadas. Durante uma semana, a sala do PETComp, localizada no Prédio CCET, do campus Bacanga em São Luís funcionou como ponto de coleta, onde alimentos não perecíveis, roupas, cobertores e itens de higiene pessoal foram recolhidos. A ação contou com a colaboração de diversos voluntários, que se dedicaram a separar, embalar e preparar os donativos para serem enviados ao Rio Grande do Sul.\r\nOs membros do PETComp destacaram que, além de contribuir materialmente, a campanha foi uma oportunidade para refletir sobre o papel da universidade na sociedade. "Nós, como estudantes e futuros profissionais, temos a responsabilidade de utilizar nossos conhecimentos e recursos para o bem comum. Ajudar quem está passando por um momento de crise é uma forma de exercer nossa cidadania e de mostrar que a ciência e a educação podem e devem estar a serviço da humanidade", afirmou um dos organizadores da coleta.', '2024-06-24', './assets/images/noticias/doacoes_petcomp.jpeg'),
	(25, 'Novo Processo Seletivo para o PETComp: Inscreva-se já!', 'O PETComp vem convidar a todos a participar da seleção para novos petianos. As inscrições para o processo seletivo PETComp estarão abertas de 19 a 21 de julho, com a primeira e segunda etapas executadas de forma remota entre os dias 22 a 24 e 25 a 26 do mesmo mês, respectivamente. O resultado estará disponível a partir do dia 29 de julho, com as atividades do discente selecionado previstas para o mês de agosto.\r\n\r\nO Programa de Educação Tutorial em Computação (PETComp), criado em 2007, abrange as áreas de pesquisa, extensão e ensino. Dessa forma, é responsável pela organização de eventos, como a Acalourada, realizada no ínicio de cada semestre para o acolher os novos ingressantes do curso. Além disso, realiza monitorias de graduação para as seguintes cadeiras: Algoritmos I, Cálculo I, Linguagem de Programação I, Matemática Discreta e Lógica e  Estrutura de Dados I.\r\n\r\nO programa oferece 6 vagas, sendo uma para a posição de bolsista, reservada para o primeiro classificado. Os requisitos para ingresso no programa são: estar entre o segundo e o sexto semestre do curso de Ciência da Computação da Universidade Federal do Maranhão (UFMA), possuir um Coeficiente de Rendimento (CR) maior ou igual a 6,0 e ter disponibilidade de 20 horas semanais para a realização das atividades, que serão feitas no turno matutino. \r\nPara mais informações, consulte o edital.', '2024-07-17', './assets/images/noticias/seletivo2024-1.png'),
	(26, 'Resultado do Processo Seletivo para o PETComp: Novos Integrantes Selecionados!', 'No dia  19 do mês de julho de 2024, deu-se início ao processo de seleção de novos petianos bolsistas e não bolsistas. Todo o processo ocorreu de forma remota, através da aplicação de um formulário a fim de analisar as motivações dos candidatos para a participação no grupo PETCOMP e dinâmica entre grupos para analisar as habilidades de trabalho em equipe.\r\n\r\nÉ com grande satisfação que divulgamos o resultado do Processo Seletivo para o Programa de Educação Tutorial em Computação (PETComp) da Universidade Federal do Maranhão. Após uma cuidadosa análise das inscrições e a realização das etapas seletivas, temos o prazer de anunciar os novos integrantes que se destacaram durante o processo.\r\n\r\nParabenizamos todos os participantes pela inscrição, empenho e dedicação durante o processo seletivo, que consistiu em duas etapas, sendo elas formulário e um desafio, respectivamente. No desafio, os candidatos puderam escolher entre monitoria, desenvolvimento e podcast . Para os novos integrantes, aguardamos ansiosamente para recebê-los em nossa equipe e iniciarmos juntos uma jornada de aprendizado, pesquisa e contribuição para a comunidade acadêmica.', '2024-08-07', './assets/images/noticias/ResultSeletivo2024.1.jpg');

-- Copiando estrutura para tabela petcom59_petcomp_db.noticias_botoes
CREATE TABLE IF NOT EXISTS `noticias_botoes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `idNoticia` int NOT NULL,
  `botaoNome` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `botaoLink` text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_idNoticia` (`idNoticia`),
  CONSTRAINT `FK_idNoticia` FOREIGN KEY (`idNoticia`) REFERENCES `noticias` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb3;

-- Copiando dados para a tabela petcom59_petcomp_db.noticias_botoes: ~17 rows (aproximadamente)
REPLACE INTO `noticias_botoes` (`id`, `idNoticia`, `botaoNome`, `botaoLink`) VALUES
	(1, 25, 'Download Edital', 'https://portalpadrao.ufma.br/proen/editais-proen/editais-2024/2024_07_Edital_PetComp_Verso_2.pdf'),
	(2, 23, 'Abrir Episódio', 'https://open.spotify.com/episode/758i4WcF47ZhgldSavGuf0?si=1c9be37a865f47d3'),
	(3, 19, 'Site de publicação do Artigo', 'https://www.even3.com.br/anais/enepet2023/658460-o-impacto-das-monitorias-academicas-na-formacao-de-alunos-de-ciencia-da-computacao--um-relato-do-petcomp-ufma/'),
	(4, 18, 'Download Edital', 'https://portalpadrao.ufma.br/proen/editais-proen/pasta-com-editais/2023_12_Edital_PetComp_Verso_1.pdf'),
	(5, 17, 'Site do PETComp', 'https://petcompufma.org/index.php'),
	(6, 15, 'Programação Completa', 'https://portalpadrao.ufma.br/site/noticias/feiradasprofissoes_folderprogramacaografica2023.pdf '),
	(7, 15, 'Site da Feira das Profissões', 'https://portalpadrao.ufma.br/profissoes'),
	(9, 8, 'Programação Enepet 2023', 'https://drive.google.com/file/d/1mJBtOIXL9Sf14V_mtBXkDA3iKh6l5jZ4/view?usp=sharing'),
	(10, 8, 'Site do Enepet 2023', 'https://www.even3.com.br/enepet2023/'),
	(11, 8, 'Instagram do Enepet', ' https://www.instagram.com/enepet.pb/'),
	(12, 9, 'Site do Enepet 2023', 'https://www.even3.com.br/enapet2023/'),
	(13, 10, 'Abrir Episódio', 'https://open.spotify.com/episode/0F9f8Reg6bHXWGkOIsbnqb'),
	(14, 12, 'Site de Oficinas e Minicursos do PETComp', 'https://petcompufma.org/minicursos.php '),
	(15, 14, 'Monitorias PETComp', 'https://petcompufma.org/monitoria.php'),
	(16, 20, 'Site de publicação do Artigo', 'https://www.even3.com.br/anais/enapet2023/667196-explorando-o-pensamento-computacional-atraves-de-jogos-educacionais-desplugados/'),
	(17, 22, 'Abrir Episódio', 'https://open.spotify.com/episode/3qVO8s24JVKJ3xvRkw4NkK?si=e2c57ecbb3404694'),
	(18, 22, 'Perfil do PETComp no Spotify', 'https://open.spotify.com/show/6fTiqItsIWohIacVtUv0Dn');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
